// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PcPartsStore.Infrastructure;

#nullable disable

namespace PcPartsStore.Infrastructure.Migrations
{
    [DbContext(typeof(PcPartsStoreContext))]
    [Migration("20251222125529_AddNewEntities")]
    partial class AddNewEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("OrderEntityProductEntity", b =>
                {
                    b.Property<int>("OrdersId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrdersId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("OrderProducts", (string)null);
                });

            modelBuilder.Entity("PcPartsStore.Infrastructure.Models.BrandEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Brands", (string)null);
                });

            modelBuilder.Entity("PcPartsStore.Infrastructure.Models.OrderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("PcPartsStore.Infrastructure.Models.ProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrandId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Products", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("PcPartsStore.Infrastructure.Models.WarrantyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Months")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Warranties", (string)null);
                });

            modelBuilder.Entity("PcPartsStore.Infrastructure.Models.CpuEntity", b =>
                {
                    b.HasBaseType("PcPartsStore.Infrastructure.Models.ProductEntity");

                    b.Property<decimal>("BaseClockGhz")
                        .HasColumnType("TEXT");

                    b.Property<int>("Cores")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Threads")
                        .HasColumnType("INTEGER");

                    b.ToTable("Cpus", (string)null);
                });

            modelBuilder.Entity("PcPartsStore.Infrastructure.Models.GpuEntity", b =>
                {
                    b.HasBaseType("PcPartsStore.Infrastructure.Models.ProductEntity");

                    b.Property<string>("Chipset")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("MemoryGb")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TdpWatts")
                        .HasColumnType("INTEGER");

                    b.ToTable("Gpus", (string)null);
                });

            modelBuilder.Entity("OrderEntityProductEntity", b =>
                {
                    b.HasOne("PcPartsStore.Infrastructure.Models.OrderEntity", null)
                        .WithMany()
                        .HasForeignKey("OrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PcPartsStore.Infrastructure.Models.ProductEntity", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PcPartsStore.Infrastructure.Models.ProductEntity", b =>
                {
                    b.HasOne("PcPartsStore.Infrastructure.Models.BrandEntity", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("PcPartsStore.Infrastructure.Models.WarrantyEntity", b =>
                {
                    b.HasOne("PcPartsStore.Infrastructure.Models.ProductEntity", "Product")
                        .WithOne("Warranty")
                        .HasForeignKey("PcPartsStore.Infrastructure.Models.WarrantyEntity", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PcPartsStore.Infrastructure.Models.CpuEntity", b =>
                {
                    b.HasOne("PcPartsStore.Infrastructure.Models.ProductEntity", null)
                        .WithOne()
                        .HasForeignKey("PcPartsStore.Infrastructure.Models.CpuEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PcPartsStore.Infrastructure.Models.GpuEntity", b =>
                {
                    b.HasOne("PcPartsStore.Infrastructure.Models.ProductEntity", null)
                        .WithOne()
                        .HasForeignKey("PcPartsStore.Infrastructure.Models.GpuEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PcPartsStore.Infrastructure.Models.BrandEntity", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PcPartsStore.Infrastructure.Models.ProductEntity", b =>
                {
                    b.Navigation("Warranty");
                });
#pragma warning restore 612, 618
        }
    }
}
