// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PcPartsStore.Infrastructure;

#nullable disable

namespace PcPartsStore.Infrastructure.Migrations
{
    [DbContext(typeof(PcPartsStoreContext))]
    [Migration("20251222122412_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("PcPartsStore.Infrastructure.Models.ProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("PcPartsStore.Infrastructure.Models.CpuEntity", b =>
                {
                    b.HasBaseType("PcPartsStore.Infrastructure.Models.ProductEntity");

                    b.Property<decimal>("BaseClockGhz")
                        .HasColumnType("TEXT");

                    b.Property<int>("Cores")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Threads")
                        .HasColumnType("INTEGER");

                    b.ToTable("Cpus", (string)null);
                });

            modelBuilder.Entity("PcPartsStore.Infrastructure.Models.GpuEntity", b =>
                {
                    b.HasBaseType("PcPartsStore.Infrastructure.Models.ProductEntity");

                    b.Property<string>("Chipset")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("MemoryGb")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TdpWatts")
                        .HasColumnType("INTEGER");

                    b.ToTable("Gpus", (string)null);
                });

            modelBuilder.Entity("PcPartsStore.Infrastructure.Models.CpuEntity", b =>
                {
                    b.HasOne("PcPartsStore.Infrastructure.Models.ProductEntity", null)
                        .WithOne()
                        .HasForeignKey("PcPartsStore.Infrastructure.Models.CpuEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PcPartsStore.Infrastructure.Models.GpuEntity", b =>
                {
                    b.HasOne("PcPartsStore.Infrastructure.Models.ProductEntity", null)
                        .WithOne()
                        .HasForeignKey("PcPartsStore.Infrastructure.Models.GpuEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
